name: PR CI

on:
  pull_request:
    branches:
      - main

env:
  GOOGLE_SERVICES_JSON_DESTINATION: app/google-services.json

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    env:
      AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Services JSON
        run: echo "${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > ${{ env.GOOGLE_SERVICES_JSON_DESTINATION }}
        env:
          FIREBASE_GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_BASE64 }}

      - name: Build Debug APK
        run: ./gradlew clean assembleDebug --no-daemon

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      AUTHORIZATION_TOKEN: ${{ secrets.AUTHORIZATION_TOKEN }}
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Google Services JSON
        run: echo "${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > ${{ env.GOOGLE_SERVICES_JSON_DESTINATION }}
        env:
          FIREBASE_GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_BASE64 }}

      - name: Run Unit Tests
        run: ./gradlew clean testDebugUnitTest --no-daemon